[ldap]
url =  ldap://ldap.openstack.local
user = cn=binduser,ou=users,dc=openstack,dc=local
password = BIND_PASS
suffix = dc=openstack,dc=local
user_tree_dn = ou=users,dc=openstack,dc=local
user_objectclass = inetOrgPerson
user_id_attribute = uid
user_name_attribute = uid
user_filter = (memberOf=cn=openstack-users,ou=groups,dc=openstack,dc=local)

group_tree_dn = ou=groups,dc=openstack,dc=local
group_objectclass = posixGroup

user_allow_create = False
user_allow_update = False
user_allow_delete = False

group_allow_create = False
group_allow_update = False
group_allow_delete = False

[identity]
driver = ldap
